export default {
	lang: 'en',
	index: {
		'index1': 'The new economy',
		'index2': 'Invite commissions',
		'index3': 'Start the journey of wealth',
		'index4': 'Financial',
		'index5': 'Top-up',
		'index6': 'Withdrawal',
		'index7': 'Invite',
		'index8': 'Place an order',
		'index9': 'Select member session',
		'index10': 'Mission Hall',
		'index11': 'Amount',
		'index12': 'Commission 0.20% | 50 Orders | LV1',
		'index13': 'Three-level proxy model',
		'index14': 'Member News',
		'index15': 'rebate',
		'index16': 'first',
		'index17': 'secondary',
		'index18': 'tertiary',
		'index19': 'Get agent commission today',
		'index20': 'Professional grab order platform',
		'index21': 'about us',
		'index22': 'company profile',
		'index24': 'Agent cooperation',
		'index25': 'We look forward to your joining',
		'index26': 'Calculate revenue',
		'index27': 'Earn commissions easily',
		'index28': 'Rule description',
		'index29': 'Keep your funds safe',
		'index30': 'EngLish'
	},
	financialManagement: {
		'index1': "Financial management",
		'index2': "Total assets",
		'index3': 'Total revenue',
		'index4': "Yesterday's earnings",
		'index5': "Income standard",
		'index6': "3 days",
		'index7': "Balance transfer",
		'index8': "Please enter the transfer amount",
		'index9': "Transfer Into",
		'index10': "financial records",
		'index11': "Storage records",
		'index12': "Extract records",
		'index13': "Extractable",
		'index14': "depositing",
		'index15': "Roll-out ",
		'index16': "Completed",
		'index17': "Under review",
		'index18': "Financial amount",
	},
	orderGrabbing: {
		'index1': "Place an order",
		'index2': "Commission has been robbed today",
		'index3': "Account freezing amount",
		'index4': "Owned today",
		'index5': "Yesterday's team commission",
		'index6': "Order Now",
		'index7': "Order description",
		'index8': "Matching grab orders...",
		'index9': "CancelSubmit",
		'index10': "Total order amount",
		'index11': "Commission",
		'index12': "Estimated refund ",
		'index13': "Ordering ",
		'index14': "Filling in the receiving information",
		'index15': "Payment successful",
		'index16': "Order submission",
		'index17': "Writing comments",
		'index18': "Order completed",
		'index19': "Total order amount",
		'index20': "Commission",
		'index21': "Estimated refund",
		'index22': "Confirm  ",
		'index23': "You don't have enough orders",
		'index24': "Would you like to get more?",
		'index25': "Invite ",
		'index26': "top-up",
		'index27': "Today's commission",
		'index28': "Completed orders"
	},
	login: {
		'index1': "Welcome",
		'index2': "LOGIN",
		'index3': "Enter your username",
		'index4': "Entert password",
		'index5': "sign IN",
		'index6': "Register a new account ",
		'index7': "sign up",
		'index8': "CREATE ACCOUNT",
		'index9': "Set password",
		'index10': "Enter the password again",
		'index11': "Alredy have an account?",

	},
	drawer: {
		'index1': "Hello",
		'index2': "Account",
		'index3': "Orders",
		'index4': "Cash Out",
		'index5': "Customer Service",
		'index6': "Invite Friends",
		'index7': "Explore",
		'index8': "Notice",
		'index9': "Account Details",
		'index10': "Recharge Record",
		'index11': "Withdrawal Record",
		'index12': "Team Report",
		'index13': "Settings",
		'index14': "Personal information",
		'index15': "Sign Out",

	},
	pay: {
		'index1': 'Account Balance',
		'index2': 'Recharge amount',
		'index3': 'Please enter the recharge amount',
		'index4': 'Your recharge amount is',
		'index5': 'Next step',
		'index6': 'Payment Information',
		'index7': 'pay',
		'index8': 'User Name ',
		'index9': 'Phone Number',
		'index10': 'Email Address',
		'index11': 'UPI ID',
		'index12': 'Purchase terms',
		'index13': 'Okay',
	},
	order: {
		'index1': 'Grab Order Record',
		'index2': 'all',
		'index3': 'Pending',
		'index4': 'Completed',
		'index5': 'Cancelled',
		'index6': 'Time',
		'index7': 'Number',
		'index8': 'Commission',
		'index9': 'Total order amount',
		'index10': 'Estimated refund',
		'index11': 'Cancel',
		'index12': 'Submit',
	},
	cashout: {
		'index1': 'Withdrawable cash',
		'index2': 'Withdraw Via',
		'index3': 'My Account',
		'index4': 'Cash withdrawal (income tax 10%)',
		'index5': "Please enter the cash withdrawal amount",
		'index6': 'Withdraw',
		'index7': 'Bank Account',
		'index8': 'Account Information',
		'index9': "Please make sure your Account Number is correct,we do not take any responsibility caused by incorrect input.",
		'index10': 'Account Number',
		'index11': 'Input Account Number',
		'index12': 'User Name ',
		'index13': 'Input Bank User Name',
		'index14': 'IFSC Code',
		'index15': 'Input IFSC Code',
		'index16': 'Bank Name',
		'index17': 'Input Bank Name',
		'index18': 'Input Branch Bank Name',
		'index19': 'Phone Number',
		'index20': 'Input Phone Number',
		'index21': 'Email',
		'index22': 'Input Email Address',
	},
	customerSerice: {
		'index1': 'Customer Service List',
		'index2': 'Copy'
	},
	inviteFriend: {
		'index1': 'invite friends',
		'index2': 'Take a commission',
		'index3': 'Invitation to experience money',
		'index4': 'Invite code:',
		'index5': 'Share links',
	},
	notice: {//公告
		'index1': 'Information title',
		'index2': 'Confirm',
		'index3': 'Message list',
		'index4': 'Information title'
	},
	accountRecord: {//帐号记录
		'index1': 'Account details',  //改到这里
		'index2': 'all',
		'index3': 'Transfer out',
		'index4': 'Transfer IN',
		'index5': 'Order unfreezing amount refund',
		'index6': 'Pay for orders'
	},
 currency:{//通用
	 'index1': 'Time selection',
	 'index2': 'Starting time',
	 'index3': 'End Time',
	 'index4': 'To be paid',
	 'index5': 'paid'
 },
 rechargeRecord:{//充值记录
 	 'index1': 'Recharge record',
 	 'index2': 'Dismissed',
 	 'index3': 'Passed',
 	 'index4': 'Top up',
 },
 withdrawalRecord:{//提现记录
 	 'index1': 'Withdrawals record',
 	 'index2': '"Cash out',
	 'index3': 'Dismissed',
 	 'index4': 'Revoked',
 	 'index5': 'Institution Name'
 },
 teamRecord: {//团队记录
 	'index1': 'Team Report',
 	'index2': 'all',
 	'index3': 'yesterday',
 	'index4': 'week',
 	'index5': 'month',
 	'index6': 'Number of teams',
	'index7': 'Team runimg',
	'index8': 'Team commisson',
	'index9': 'My commission',
	'index10': 'First',
	'index11': 'Secondary',
	'index12': 'Tertiary',
},
 teamRecord: {//团队记录
 	'index1': 'Team Report',
 	'index2': 'all',
 	'index3': 'yesterday',
 	'index4': 'week',
 	'index5': 'month',
 	'index6': 'Number of teams',
	'index7': 'Team runimg',
	'index8': 'Team commisson',
	'index9': 'My commission',
	'index10': 'First',
	'index11': 'Secondary',
	'index12': 'Tertiary',
},
	personalCenter:{//	个人中心
	'index1': 'Personal information',
	'index2': 'Invitation code',
	'index3': 'My Phone Number',
	'index4': 'My Bank Card',
	'index5': 'Password Management',
	'index6': 'Shipping Address',
	'index7': 'Withdraw Via',
	'index8': 'My Account',
	'index9': 'IFSC Code',
	'index10': 'Bank Name',
	'index11': 'Branch Bank Name',
	'index12': 'Phone Number',
	'index13': 'Email',
	'index14': 'Modify information',
	},
	adressManage:{//	地址管理
	'index1': 'Add address',
	'index2': 'Receive identity information',
	'index3': 'Receiver',
	'index4': 'Please enter your real name',
	'index5': 'Please enter your phone number',
	'index6': 'Delivery address information',
	'index7': 'address',
	'index8': 'Please enter a region',
	'index9': 'Please enter detailed address',
	'index10': 'Set as the default address',
	'index11': 'Delete',
	'index12': 'Okay',
	'index13': 'Shipping Address',
	},
	ToastProxy:{//	弹窗代理
	'index1': "Yesterday's agency income",
	'index2': 'New people',
	'index3': 'Team order commission',
	'index4': "Yesterday's total income",
	'index5': 'Invite to Get More',
	},
	versionUpdate:{//	版本更新
	'index1': "New version update",
	'index2': 'Update Now'
	},
  noneNet:{ //无网络
		'index1': "Network connection failed, click retry or check network",
		'index2': 'No data',
	}
}