export default {
 	lang: 'en',
 	index: {
 		'index1': 'The new economy',
		'index2':'Invite commissions',
 		'index3': 'Start the journey of wealth',
		'index4':'Financial',
		'index5':'Top-up',
		'index6':'Withdrawal',                 
		'index7':'Invite',
		'index8':'Place an order',
		'index9':'Select member session',
		'index10':'Mission Hall',
		'index11':'Amount',
		'index12':'Commission 0.20% | 50 Orders | LV1',
		'index13':'Three-level proxy model',
		'index14':'Member News',
		'index15':'rebate',
		'index16':'first',
		'index17':'secondary',
		'index18':'tertiary',
		'index19':'Get agent commission today',
		'index20':'Professional grab order platform',
		'index21':'about us',
		'index22':'company profile',
		'index24':'Agent cooperation',
		'index25':'We look forward to your joining',
		'index26':'Calculate revenue',
		'index27':'Earn commissions easily',                                        
		'index28':'Rule description',
		'index29':'Keep your funds safe',
		'index30':'EngLish'
 	},
	financialManagement:{
		'index1':"Financial management",
		'index2':"Total assets",
		'index3':'Total revenue',
		'index4':"Yesterday's earnings",
		'index5':"Income standard",
		'index6':"3 days",
		'index7':"Balance transfer",
		'index8':"Please enter the transfer amount",
		'index9':"Transfer Into",
		'index10':"financial records",
		'index11':"Storage records",
		'index12':"Extract records",
		'index13':"Extractable",
		'index14':"depositing",
		'index15':"Roll-out ",
		'index16':"Completed",
		'index17':"Under review",

	}
 }
